# version: '3.8'

# services:
#   db:
#     image: postgres:16
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB: schooldb
#       POSTGRES_USER: schooluser
#       POSTGRES_PASSWORD: password

#   web:
#     build: .
#     command: >
#       sh -c "
#       python manage.py migrate &&
#       gunicorn video_processor.wsgi:application --bind 0.0.0.0:8000"
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

# volumes:
#   postgres_data:
#-----------------------------------------------

version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: video_processor
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: password

  backend:
    build: ./backend
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn video_processor.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  frontend:
    build: 
      context: ./frontend/video-processor-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend


volumes:
  postgres_data: